$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$templatesDir = Join-Path $root "templates"
$docsDir = Join-Path $root "docs"
$catalogPath = Join-Path $docsDir "template_catalog.md"

$templates = Get-ChildItem $templatesDir -Filter "*.json" | Sort-Object Name | ForEach-Object {
  Get-Content $_.FullName -Raw -Encoding utf8 | ConvertFrom-Json
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Template Catalog")
$lines.Add("")
$lines.Add('Generated by `scripts/generate_template_catalog.ps1`.')
$lines.Add("")
$lines.Add("| Template ID | Category | Title | Ratio | Style | Quality | Face Strength |")
$lines.Add("| --- | --- | --- | --- | --- | --- | ---: |")

foreach ($template in $templates) {
  $lines.Add("| $($template.template_id) | $($template.category) | $($template.title) | $($template.ratio) | $($template.style) | $($template.options.quality) | $($template.options.face_strength) |")
}

$lines.Add("")
$lines.Add("## Usage")
$lines.Add("")
$lines.Add("Generate prompt:")
$lines.Add("")
$lines.Add('```bash')
$lines.Add("npm run generate <template_id>")
$lines.Add('```')
$lines.Add("")
$lines.Add("Run mock image task:")
$lines.Add("")
$lines.Add('```bash')
$lines.Add("npm run image <template_id>")
$lines.Add('```')
$lines.Add("")
$lines.Add("Run single-template smoke test without npm:")
$lines.Add("")
$lines.Add('```powershell')
$lines.Add("powershell -ExecutionPolicy Bypass -File scripts/smoke_test.ps1 -TemplateId <template_id>")
$lines.Add('```')

$lines | Set-Content -Path $catalogPath -Encoding utf8
Write-Host $catalogPath
